Repository oti-team4/team4_lms, pull requests merged in 2023-01, with the labels that each got.

#8 #7 출결 조회 및 출석 처리 기능 구현 완료
  .gitignore
  .settings/org.eclipse.wst.common.component
  src/main/java/com/team4/myapp/HomeController.java
  src/main/java/com/team4/myapp/MainController.java
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/controller/dto/CalendarDto.java
  src/main/java/com/team4/myapp/attendance/dao/IAttendanceRepository.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/attendance/model/Attendance.java
  src/main/java/com/team4/myapp/attendance/service/AttendanceService.java
  src/main/java/com/team4/myapp/attendance/service/IAttendanceService.java
  src/main/resources/spring/application-config.xml
  src/main/webapp/WEB-INF/resources/calendar/js/calendar.js
  src/main/webapp/WEB-INF/resources/home/css/styles.css
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
  src/main/webapp/WEB-INF/views/fragment/head.jsp
  src/main/webapp/WEB-INF/views/fragment/nav.jsp
  src/main/webapp/WEB-INF/views/index.jsp
Labels: 기능구현, 추가 구현 필요

#10 resources 경로 수정
  src/main/java.zip
  src/main/java/com/team4/myapp/MainController.java
  src/main/webapp/WEB-INF/resources/home2/assets/favicon.ico
  src/main/webapp/WEB-INF/resources/home2/assets/img/about/1.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/about/2.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/about/3.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/about/4.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/close-icon.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/header-bg.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/logos/facebook.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/logos/google.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/logos/ibm.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/logos/microsoft.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/map-image.png
  src/main/webapp/WEB-INF/resources/home2/assets/img/navbar-logo.svg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/1.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/2.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/3.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/4.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/5.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/portfolio/6.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/team/1.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/team/2.jpg
  src/main/webapp/WEB-INF/resources/home2/assets/img/team/3.jpg
  src/main/webapp/WEB-INF/resources/home2/css/styles.css
  src/main/webapp/WEB-INF/resources/home2/js/scripts.js
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/fragment/head.jsp
  src/main/webapp/WEB-INF/views/home.jsp
  src/main/webapp/WEB-INF/views/home2.jsp
Labels: 화면 구현

#11 #7 퇴근처리 기능
  .settings/org.eclipse.wst.common.component
  log4j.xml
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/dao/IAttendanceRepository.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/attendance/model/CalendarDto.java
  src/main/java/com/team4/myapp/attendance/service/AttendanceService.java
  src/main/java/com/team4/myapp/attendance/service/IAttendanceService.java
  src/main/java/com/team4/myapp/member/controller/MemberController.java
  src/main/webapp/WEB-INF/resources/calendar/js/calendar.js
  src/main/webapp/WEB-INF/resources/home/assets/favicon.ico
  src/main/webapp/WEB-INF/resources/home/assets/img/about/1.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/about/2.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/about/3.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/about/4.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/close-icon.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/header-bg.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/logos/facebook.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/logos/google.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/logos/ibm.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/logos/microsoft.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/map-image.png
  src/main/webapp/WEB-INF/resources/home/assets/img/navbar-logo.svg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/1.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/2.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/3.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/4.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/5.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/portfolio/6.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/team/1.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/team/2.jpg
  src/main/webapp/WEB-INF/resources/home/assets/img/team/3.jpg
  src/main/webapp/WEB-INF/resources/home/css/styles.css
  src/main/webapp/WEB-INF/resources/home/js/scripts.js
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
  src/main/webapp/WEB-INF/views/fragment/footer.jsp
  src/main/webapp/WEB-INF/views/fragment/head.jsp
  src/main/webapp/WEB-INF/views/fragment/nav.jsp
  src/main/webapp/WEB-INF/views/home.jsp
Labels: 기능구현, 질문, 추가 구현 필요

#23 [#20]조퇴 기능 구현 완료
  .settings/org.eclipse.wst.common.component
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/dao/IAttendanceRepository.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/attendance/service/AttendanceService.java
  src/main/java/com/team4/myapp/attendance/service/IAttendanceService.java
  src/main/java/com/team4/myapp/out/dao/IOutRepository.java
  src/main/java/com/team4/myapp/out/dao/OutMapper.xml
  src/main/java/com/team4/myapp/out/model/OutDto.java
  src/main/java/com/team4/myapp/out/service/IOutService.java
  src/main/java/com/team4/myapp/out/service/OutService.java
  src/main/java/com/team4/myapp/util/scheduler/AttendanceScheduler.java
  src/main/resources/spring/application-config.xml
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
Labels: 기능구현

#27 외출 관련 기능 구현
  .settings/org.eclipse.wst.common.component
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/dao/IAttendanceRepository.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/attendance/service/AttendanceService.java
  src/main/java/com/team4/myapp/attendance/service/IAttendanceService.java
  src/main/java/com/team4/myapp/out/dao/IOutRepository.java
  src/main/java/com/team4/myapp/out/dao/OutMapper.xml
  src/main/java/com/team4/myapp/out/model/OutListDto.java
  src/main/java/com/team4/myapp/out/service/IOutService.java
  src/main/java/com/team4/myapp/out/service/OutService.java
  src/main/java/com/team4/myapp/util/scheduler/AttendanceScheduler.java
  src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
Labels: 기능구현

#52 css 수정
  src/main/java/com/team4/myapp/AMController.java
  src/main/java/com/team4/myapp/TestBoardController.java
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/model/CalendarDto.java
  src/main/java/com/team4/myapp/attendance/model/dto/AttendanceDto.java
  src/main/java/com/team4/myapp/attendance/service/AttendanceService.java
  src/main/java/com/team4/myapp/attendance/service/IAttendanceService.java
  src/main/java/com/team4/myapp/cause/controller/CauseController.java
  src/main/java/com/team4/myapp/cause/dao/CauseMapper.xml
  src/main/java/com/team4/myapp/cause/dao/ICauseRepository.java
  src/main/java/com/team4/myapp/cause/service/CauseService.java
  src/main/java/com/team4/myapp/cause/service/ICauseService.java
  src/main/java/com/team4/myapp/interceptor/AuthInterceptor.java
  src/main/java/com/team4/myapp/interceptor/LoginInterceptor.java
  src/main/java/com/team4/myapp/util/scheduler/AttendanceScheduler.java
  src/main/webapp/WEB-INF/resources/calendar/fullcalendar/packages/core/main.css
  src/main/webapp/WEB-INF/resources/calendar/js/calendar.js
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
  src/main/webapp/WEB-INF/views/lecture/index.jsp
Labels: 화면 구현

#55 시간 subString 다시 작성 , 지각 색상 변경
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/attendance/model/CalendarDto.java
Labels: 화면 구현

#62 스케줄러 시간 변경
  src/main/java/com/team4/myapp/util/scheduler/AttendanceScheduler.java
Labels: 수정

#63 최종 수정
  src/main/java/com/team4/myapp/attendance/controller/AttendanceController.java
  src/main/java/com/team4/myapp/attendance/dao/IAttendanceRepository.java
  src/main/java/com/team4/myapp/attendance/dao/mapper/AttendanceMapper.xml
  src/main/java/com/team4/myapp/cause/controller/CauseController.java
  src/main/java/com/team4/myapp/cause/dao/mapper/CauseMapper.xml
  src/main/java/com/team4/myapp/cause/model/dto/CauseListDto.java
  src/main/java/com/team4/myapp/cause/service/CauseService.java
  src/main/webapp/WEB-INF/resources/cause_list/js/main.js
  src/main/webapp/WEB-INF/views/calendar/userCalendar.jsp
  src/main/webapp/WEB-INF/views/cause/write.jsp
Labels: 기능구현, 수정완료
